config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'home/index'
  resources :shops

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :shop
end

app/models/shop.rb
class Shop < ApplicationRecord
    has_one :user
    has_many :products
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  belongs_to :shop
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
    skip_before_action :authenticate_user!, only: :index
    def index
        @shops = Shop.all
    end

    def new
        if current_user.shop.present?
            render 'index'
        else
            @shop = Shop.new
        end
    end

    def create
        if @shop = Shop.create(shop_params)
            current_user.update_attributes(shop_id: @shop.id)
            redirect_to @shop
        else
            render 'new'
        end
    end

    def show
        @shop = Shop.find(params[:id])
    end

    private
        def shop_params
            params.require(:shop).permit(:name, :address, :phone_number)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
%h1 Welcome #{current_user.email}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Mockopedia
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    - if current_user
      = link_to 'Sign Out', destroy_user_session_path, method: :delete
    - else
      = link_to 'Sign In', new_user_session_path
      = link_to 'Sign Up', new_user_registration_path
    - if notice
      %p.alert.alert-success= notice
    - if alert
      %p.alert.alert-danger= alert
    = yield

app/views/shops/index.html.haml
%h1 Shop List
%button
    - if current_user.shop.present?
        = link_to 'Your Shop', shop_path(current_user.shop)
    - else
        = link_to 'Create Your Shop', new_shop_path
%br
%table
    %thead
        %th Name
        %th Address
        %th Phone Number
    %br
    %tbody
        - @shops.each do |shop|
            %tr
                %td= shop.name
                %td= shop.address
                %td= shop.phone_number

app/views/shops/new.html.haml
%h1 Create a New Shop
= simple_form_for(@shop, url: shops_path, method: :post) do |f|
    = f.input :name, label: 'Your shop name'
    = f.input :address
    = f.input :phone_number
    = f.button :submit

app/views/shops/show.html.haml
%h1 Your Shop
%h2= @shop.name
%h3 Address
%p= @shop.address
%h3 Phone Number
%p= @shop.phone_number